# Generated by Django 5.0.7 on 2024-08-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Price', models.IntegerField()),
                ('Types', models.CharField(choices=[('wood', 'wood'), ('plastic', 'plastic'), ('steel', 'steel')], max_length=20)),
                ('Details', models.TextField()),
            ],
        ),
    ]
